"==============================================================================
" File: linux.vim
"------------------------------------------------------------------------------
" Description: This file adds custom syntax highlighting for a long list of
"              linux commands of a ubuntu/mint distribution.
"------------------------------------------------------------------------------
" Authors: Danny Sarraf
"------------------------------------------------------------------------------
" URL: https://github.com/dddansar/vimrc
"------------------------------------------------------------------------------
" Copyright: MIT License
"
" Copyright (c) 2026 Danny Sarraf
"
" Permission is hereby granted, free of charge, to any person obtaining a copy
" of this software and associated documentation files (the "Software"), to deal
" in the Software without restriction, including without limitation the rights
" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
" copies of the Software, and to permit persons to whom the Software is
" furnished to do so, subject to the following conditions:
"
" The above copyright notice and this permission notice shall be included in
" all copies or substantial portions of the Software.
"
" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
" SOFTWARE.
"==============================================================================


" Exit if the file was already loaded
if exists("b:linux_loaded")
  finish
endif
let g:linux_loaded = 1


" compgen -c " List all the linux commands you could run.

hi  link  LinuxCommands Statement
syn keyword LinuxCommands 7z 7za 7zr accessdb aconnect acpidbg addgnupghome addgroup addpart addr2line adduser agetty alert alsa alsabat alsactl alsaloop alsamixer alsatplg alsaucm amidi amixer anacron apg apgbfm aplay aplaymidi applygnupgdefaults appres appstreamcli apropos apt arecord arecordmidi arm2hpdl arp arpd arptables as aseqdump aseqnet aspell atobm attr avahi awk axfer b2sum badblocks baobab base32 base64 basename basenc bash bashbug bc bdftopcf bdftruncate bg bind biosdecode bitmap blkdeactivate blkdiscard blkid blkzone blockdev bluemoon bluetoothctl bluetoothd bmtoa boltctl bpftool break bridge brltty broadwayd browse btattach btmgmt btmon btrfs btrfsck btrfstune builtin bunzip2 busctl busybox bwrap bzcat bzcmp bzdiff bzegrep bzexe bzfgrep bzgrep bzip2 bzip2recover bzless bzmore containedin=.*String.*,shSingleQuote
syn match LinuxCommands "\<c++"
syn keyword LinuxCommands c89 c99 caller cancel capsh captain captoinfo cat catfish catman cc ccsm cd celluloid cfdisk cgdisk chacl chage chardet chardetect charmap chat chattr chcon chcpu chfn chgpasswd chgrp chmem chmod choom chown chpasswd chroot chrt chsh chvt cifscreds cifsdd ciptool cjxl ckbcomp cksum clear cmp codepage col colcrt colormgr colrm column combinediff comm command compgen compiz complete compopt compose compton continue coproc coredumpctl corelist cp cpan cpgr cpio cpp cppw cpupower cron crontab cryptsetup csplit ctrlaltdel ctstat cupsaccept cupsctl cupsd cupsdisable cupsenable cupsfilter cupsreject cupstestppd curl cut cvt cvtsudoers containedin=.*String.*,shSingleQuote
syn keyword LinuxCommands dash date dbxtool dc dcb dccleancrw dcfujigreen dcfujiturn dcfujiturn16 dconf dcparse dcraw dd ddstdecode deallocvt debconf debugfs debugreiserfs declare dehtmldiff delgroup delpart deluser delv depmod dequote devdump devlink df dhclient dhcpcd dialog diff diff3 dig dir dircolors dirdiff dirmngr dirname dirs dirsplit disown djxl dkms dmesg dmeventd dmidecode dmraid dmsetup dmstats dnsdomainname dnsmasq domainname dosfsck dosfslabel dpkg drawing driverless du dumpe2fs dumpkeys dvipdf dwp e2freefrag e2fsck e2image e2label e2mmpstatus e2scrub e2undo e4crypt e4defrag ebtables echo ecryptfsd ed edit editdiff editor editres efibootdump efibootmgr eglinfo egrep eject elfedit enable enc2xs encguess env envsubst eps2eps eqn erb es2tri espdiff ethtool eutp eval eview evim evince ex exec exfat2img exfatlabel expiry export expr factor faillock faillog fakeroot fallocate fatlabel fc fdisk ffmpegthumbnailer fg fgconsole fgrep file file2brl filefrag filetype filterdiff finalrd find findfs findmnt firefox fixcvsdiff fixparts flatpak flipdiff flock fmt fold fonttosfnt foo2ddst foo2hbpl2 foo2hiperc foo2hp foo2lava foo2oak foo2qpdl foo2slx foo2xqx foo2zjs free fsadm fsck fsfreeze fstrim ftp funzip fuser fusermount fusermount3 fwupdmgr fwupdtool containedin=.*String.*,shSingleQuote
syn match LinuxCommands "\<g++"
syn keyword LinuxCommands gamemoded gamemodelist gamemoderun gamma4scanimage gapplication gatttool gcalccmd gcc gcore gcov gdb gdbtui gdbus gdialog gdisk gem gencat genisoimage genl geqn GET getcap getcifsacl getconf geteltorito getent getfacl getfattr gethostip getkeycodes getopt getopts getpcaps gettext gettextize getty getweb ghostscript gio gipddecode git gitdiff gitdiffview glxdemo glxgears glxheads glxinfo gmake gmplayerdvd gold gparted gpasswd gpg gpgconf gpgparsemail gpgsm gpgsplit gpgtar gpgv gpic gprof gprofng grep grepdiff gresource groff grog grops grotty groupadd groupdel groupmems groupmod groups grpck grpconv grpunconv gs gsbj gsdj gsdj500 gsettings gsf gslj gslp gsnd gtbl gtf gucharmap gufw gunzip gview gvim gvimdiff gvimtutor gzexe gzip h2ph h2xs halt hardinfo hardlink hash hbpldecode hciattach hciconfig hcitool hd hdparm head help helpztags hex2hcd hexdump hipercdecode history host hostid hostname hostnamectl html2markdown htop hypnotix i386 iceauth ico iconv iconvconfig id idevicebackup idevicebackup2 idevicecrashreport idevicedate idevicedebug idevicedebugserverproxy idevicediagnostics ideviceenterrecovery ideviceimagemounter ideviceinfo ideviceinstaller idevicename idevicenotificationproxy containedin=.*String.*,shSingleQuote
syn keyword LinuxCommands idevicepair ideviceprovision idevicescreenshot idevicesetlocation idevicesyslog iecset ifconfig iftop ifuse imdbpy info infobrowser infocmp infotocap init inputattach insmod install installkernel instmodsh integritysetup interdiff inxi ionice ip ip6tables ipcmk ipcrm ipcs ipmaddr ippevepcl ippeveprinter ippeveps ippfind ipptool iptables iptunnel irb irqbalance isadump isaset ischroot isodump isohybrid isoinfo isosize isovfy iwconfig iwevent iwgetid iwlist iwpriv iwspy jobs join journalctl jpgicc jxlinfo kbdinfo kbdrate kbxutil kerneloops keyctl kill killall killall5 kmod kmodsign kpartx l2ping l2test la last lastb lastlog lavadecode lcf ld ldattach ldconfig ldd less lessecho lessfile lesskey lesspipe lexgrog libnetcfg libreoffice lightdm linkicc linux32 linux64 listres ln lnstat loadkeys loadunimap local localc locale localectl localedef locate lodraw loffice lofromtemplate logger login loginctl logname logout logrotate logsave loimpress look losetup loweb lowriter lp lpadmin lpc lpinfo lpmove lpoptions lpq lpr lprm lpstat ls lsattr lsblk lscpu lsdiff lshw lsinitramfs lsipc lslocks lslogins lsmem containedin=.*String.*,shSingleQuote
syn keyword LinuxCommands lsmod lsns lsof lspci lspcmcia lspgpot lspower lss16toppm lsusb ltrace luksformat lvchange lvconvert lvcreate lvdisplay lvextend lvm lvmconfig lvmdiskscan lvmdump lvmpolld lvmsadc lvmsar lvreduce lvremove lvrename lvresize lvs lvscan lz lzcat lzcmp lzdiff lzegrep lzfgrep lzgrep lzless lzma lzmainfo lzmore m2300w m2400w make man mandb manpath mapfile mapscrn mattrib mawk mbadblocks mcat mcd mcheck mcomp mcookie mcopy md5pass md5sum mdadm mdel mdeltree mdig mdir mdmon mdsearch mdu memdiskfind menulibre mesg metacity mformat mid3cp mid3iconv mid3v2 mimeopen mimetype min12xxw minfo mintBackup mintbackup mintchat mintdesktop mintdrivers mintinstall mintlocale mintreport mintsources mintstick mintupdate mintwelcome mkdir mkdiskimage mkdosfs mke2fs mkfifo mkfontdir mkfontscale mkfs mkinitramfs mkisofs mklostund mkmanifest mknod mkntfs mkreiserfs mksquashfs mkswap mktemp mkzftree mlabel mmcli mmd mmount mmove ModemManager modinfo modprobe moggsplit mokutil more mount mountpoint mousetweaks mpartition mrd mren mscompress msexpand msgattrib msgcat msgcmp msgcomm msgconv msgen msgexec msgfilter msgfmt msggrep msginit msgmerge msgunfmt msguniq mshortname mshowfat mt mtools mtoolstest mtr mtype mugshot mv mxtar mzip namei nameif nano nawk nc ncdu neofetch neqn net netaddr netcat netplan netstat networkctl NetworkManager newgrp newusers nft ngettext containedin=.*String.*,shSingleQuote
syn keyword LinuxCommands nice nisdomainname nl nm nmblookup nmcli nmtui nohup nologin nproc nroff nsenter nslookup nstat nsupdate ntfscat ntfsclone ntfscluster ntfscmp ntfscp ntfsdecrypt ntfsfallocate ntfsfix ntfsinfo ntfslabel ntfsls ntfsmove ntfsrecover ntfsresize ntfssecaudit ntfstruncate ntfsundelete ntfsusermap ntfswipe numfmt oakdecode obexctl objcopy objdump oclock od onboard openssl openvpn openvt opldecode orca ownership p7zip pacat pacmd pactl pager pamon paperconf paperconfig paplay parec parecord parted partprobe partx passwd paste pastebin pasuspender patch patchview pathchk pavucontrol pax11publish pccardctl pdb3 pdf2dsc pdf2ps pdfattach pdfdetach pdffonts pdfimages pdfinfo pdfseparate pdfsig pdftocairo pdftohtml pdftoppm pdftops pdftotext pdfunite peekfd peglgears perf perl perlbug perldoc perli11ndoc perlivp perlthanks pf2afm pfbtopfa pgrep pic pico piconv pidof pidwait pinentry ping ping4 ping6 pinky pipewire pix pkaction pkcheck pkcon pkexec pkgconf pkill pkmon pkttyagent pl2pm pldd plipconfig plocate plog plymouth plymouthd pmap pnm2ppa pod2html pod2man pod2text pod2usage podchecker poff pon popd poweroff powerprofilesctl ppdc ppdhtml ppdi ppdmerge ppdpo pphs ppmtolss16 pppd pppdump pppstats pptp pptpsetup pr precat preconv prename preunzip prezip print printafm printenv printf prlimit prove prtstat ps2ascii ps2epsi ps2pdf ps2pdf12 ps2pdf13 ps2pdf14 ps2pdfwr ps2ps ps2ps2 ps2txt psfaddtable psfgettable psfstriptable psfxtable psicc pslog pstree ptar ptardiff containedin=.*String.*,shSingleQuote
syn keyword LinuxCommands ptargrep ptx pushd pvchange pvck pvcreate pvdisplay pvmove pvremove pvresize pvs pvscan pwck pwconv pwd pwdx pwunconv py3clean py3compile py3versions pydoc3 pygettext3 pygmentize python3 pzstd qpdldecode qr quote rake ranlib rarp rbash rctest rdate rdma rdoc read readarray readelf readlink readonly readprofile realpath reboot recountdiff red rediff reiserfsck reiserfstune rename rendercheck renice reset resize2fs resizecons resizepart resolvconf resolvectl rev rfcomm rfkill rgrep rgview rgvim rhythmbox ri rm rmdir rmmod rmt rnano route routel rpcclient rpcgen rrsync rstart rstartd rsync rsyslogd rtacct rtcwake rtfm rtkitctl rtla rtmon rtstat ruby runcon runlevel runuser rview rvim containedin=.*String.*,shSingleQuote
syn keyword LinuxCommands saned savelog sbattach sbkeysync sbsiglist sbsign sbvarsign sbverify scalar scanimage scp screendump script scriptlive scriptreplay sdiff sdptool seahorse search4files sed see select sensors seq service sessreg setarch setcap setcifsacl setfacl setfattr setfont setkeycodes setleds setlogcons setmetamode setpci setpriv setsid setterm setupcon setvesablank setvtrgb setxkbmap sfdisk sftp sg sgdisk sh sha1pass sha1sum sha224sum sha256sum sha384sum sha512sum shadowconfig shasum shift shopt showconsolefont showkey showrgb shred shuf shutdown size skill slabtop slattach sleep slogin slxdecode smbcacls smbclient smbcquotas smbget smbinfo smbpasswd smbspool smbtar smbtree smproxy snice soelim soffice sort spdsend splain split splitdiff splitfont sqfscat sqfstar ss ssh startcaja startx startxfce4 stat stdbuf sticky strace streamzip strings strip stty su sudoedit sudoreplay sulogin sum suspend svn svnadmin svnauthz svnbench svndiff svndiffview svndumpfilter svnfsfs svnlook svnmucc svnrdump svnserve svnsync svnversion swaplabel swapoff swapon switcherooctl sync sysctl syslinux syslinux2ansi systemctl systemd containedin=.*String.*,shSingleQuote
syn keyword LinuxCommands t1ascii t1asm t1binary t1disasm t1mac t1unmac tabs tac tail tar tarcat taskset tbl tc tclsh tcpdump tee telinit telnet tempfile test testparm tgz thermald thingy Thunar thunar thunderbird tic tificc time timedatectl timeout times timeshift tipc tkcvs tkdiff tkdirdiff tldr tload tmux tnftp toe top touch touchall tput tr tracepath transicc transset trap troff truncate trust tset tsort tty tune2fs turbostat type typeset tzselect ucf ucfq ucfr uclampset ucs2any udevadm udisksctl ufw ul ulimit umask umount unalias uname uncompress unexpand uniq unlink unlzma unmkinitramfs unopkg unshare unsquashfs until unwrapdiff unxz unzip unzipsfx unzstd updatedb upower uptime usbip usbipd usbmuxd usbreset useradd userdel usermod users utmpdump uuidd uuidgen uuidparse uz validlocale varlinkctl vcstime vdir vdpa veritysetup vgcfgbackup vgcfgrestore vgchange vgck vgconvert vgcreate vgdisplay vgexport vgextend vgimport vgimportclone vgmerge vgmknodes vgreduce vgremove vgrename vgs vgscan vgsplit vi view viewres vigr vim vimdiff vimtutor vipw visudo vkgears vlcdvd vmstat vmwarectrl vpddecode vstp containedin=.*String.*,shSingleQuote
syn keyword LinuxCommands wait wall warpinator watch watchgnupg wc wdctl wget whatis whereis which whiptail who whoami wipefs wish wmctrl write x11perf x11perfcomp xargs xauth xbiff xbrlapi xcalc xclipboard xclock xcmsdb xconsole xcursorgen xcutsel xditview xdpyinfo xdriinfo xed xedit xeglgears xeglthreads Xephyr xev xeyes xfd xfdesktop xflock4 xfontsel xfrun4 xfsettingsd xfwm4 xgamma xgc xgettext xhost xiccd xinit xinput xkbbell xkbcomp xkbevd xkbprint xkbvleds xkbwatch xkeystone xkill xload xlogo xlsatoms xlsclients xlsfonts xmag xman xmessage xmodmap xmore Xorg xprop xqxdecode xrandr xrdb xreader xrefresh xset xsetmode xsetpointer xsetroot xsetwacom xsm xstdcmap xsubpp xvidtune xviewer xvinfo Xwayland xwd xwininfo xwud xxd xz xzcat xzcmp xzdiff xzegrep xzfgrep xzgrep xzless xzmore yelp yes ypdomainname zcat zcmp zdiff zdump zegrep zenity zfgrep zforce zgrep zic zip zipcloak zipdetails zipgrep zipinfo zipnote zipsplit zjsdecode zless zmore znew zramctl zstd zstdcat zstdgrep zstdless zstdmt containedin=.*String.*,shSingleQuote

