" ============================================================================
" NOTE: DS: Function header comments generated by Claude API.
"------------------------------------------------------------------------------
" NOTE: I keep my claude.vim/*.md files empty as I prefer the default settings
"       and it saves some cost by sending less data through the API and if I
"       want Claude to behave a certain way, I'd rather just tell it
"       specifically how to behave at that time.
"------------------------------------------------------------------------------
" NOTE: I disabled chat folding by adding g:claude_enable_folding = 0
"------------------------------------------------------------------------------
" NOTE: Here is a list of questions that I asked Claude to update this file:
"------------------------------------------------------------------------------
" You: When I open a large file and I try to send a message to claude. I get an error: Error: executing job failed: Argument list too long. How can I updated claude.vim to fix this error for large files when interacting with claude? show the proposed fix in this chat.
" You: Now I get the following error: Unknown Claude protocol output: "{"type":"error","error":{"type":"invalid_request_error","message":"prompt is too long: 315952 tokens > 200000 maximum"},"request_id":"req_011CYX2LSayJnEjuQiQYMKcq"}". propose a fix in this chat.
" You: how can I edit claude.vim to increase the context window form 200k to 1m?
" --> First it said you can't...
"   You: according to the website https://platform.claude.com/docs/en/build-with-claude/context-windows:
"   Claude Opus 4.6, Sonnet 4.6, Sonnet 4.5, and Sonnet 4 support a 1-million token context window. This extended context window allows you to process much larger documents, maintain longer conversations, and work with more extensive codebases.
"   To use the 1M token context window, include the context-1m-2025-08-07 beta header in your API requests:
"   curl https://api.anthropic.com/v1/messages \
"     -H "x-api-key: $ANTHROPIC_API_KEY" \
"     -H "anthropic-version: 2023-06-01" \
"     -H "anthropic-beta: context-1m-2025-08-07" \
"     -H "content-type: application/json" \
"   You: so how do I update claude.vim to support 1m tokens?
"   --> Now it gives correct answer
" You: What latest version should I use for "let g:claude_model"?
" You: Help me understand what the claude.vim file does by adding a lot of comments. Add comments that explain in detail what each function does.
" You: Show a map in this chat of how the functions in claude.vim are connected
" You: Update claude.vim to print the token usage and cost in the chat.
" You: How can I modify the system prompt to only have the "You:" line?
" You: The printed token usage is not accurate, how can I make it more accurate?
" --> took some back and forth to get this one right but it worked in the end.
" You: What value should I set 'max_tokens' to?
" You: When you search through internet links you are getting the message: elinks Update your browser Your browser isn't supported anymore. To continue your search, upgrade to a recent version. Propose a fix for this issue.
" --> lots of back and forth until it found a solution that works by using curl and changing from google to brave...
" You: How can I set g:claude_map_cancel_response = "<c-c>" and have it only affect the claude chat window and not any other file?
" You: I want to have the functions print "claude-sonnet-4-6:" using g:claude_model instead of printing "Claude:"
" You: I asked you to show me a diff before making the changes yet you gave me an error...
"      Unknown Claude protocol output: "{"type":"error","error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"},"request_id":"req_011CZwmNjfkhCsMGwEaheCjt"}"
"      Suggest a fix for the error in claude.vim in this chat.
" You: When I ask the claude api to compare 2 websites, I believe the final cost is a bit too high. Are there ineffiencies in the code that may be causing the issue that I'm seeing. See if you can find any issues that may cause wasteful and inefficient code.
" You: I want an option to use batch api in my claude api in vim. How can I add it as an additional option?
" You: Add support for qwen local AI!
" You: Add support for OpenAI/ChatGPT and Gemini AI!
" ============================================================================


" ============================================================================
" You: write me a short poem of 20 lines
" Claude: Here's a short poem for you! 🌟
"
"    ---
"
"    **The Dance of Time**
"
"    The sun rises slow and bright,
"    Painting the sky with golden light.
"    The birds begin their morning song,
"    A melody that carries long.
"
"    The breeze whispers through the trees,
"    Carrying secrets on the keys.
"    The river flows without a care,
"    Its gentle voice fills the air.
"
"    The flowers bloom in colors bold,
"    A story waiting to be told.
"    The mountains stand through rain and snow,
"    Their ancient wisdom starts to show.
"
"    The stars appear when day is done,
"    Replacing now the fading sun.
"    The moon casts silver on the sea,
"    A timeless dance for you and me.
"
"    And when the night gives way to dawn,
"    The world begins to carry on.
"    For time is just a gentle tide,
"    With beauty flowing by each side.
"
"    ---
"
"    Hope you enjoyed it! 😊
" (Token usage - Input: 1235+0c+0r ($0.0037), Output: 207 ($0.0031), Total: ($0.0068))
" ============================================================================


" ============================================================================
" Function maps showing how all the functions are connected in claude.vim
" ============================================================================
"
"   ╔══════════════════════════════════════════════════════════════════════════╗
"   ║  ENTRY POINTS  (keybindings / Ex commands / autocommands)                ║
"   ╚══════════════════════════════════════════════════════════════════════════╝
"
"     VimEnter autocmd
"         └──► SetupClaudeKeybindings()
"                   ├──► ClaudeImplement()   (:ClaudeImplement / <leader>ci)
"                   ├──► OpenClaudeChat()    (:ClaudeChat      / <leader>cc)
"                   └──► CancelClaudeResponse()  (:ClaudeCancel / <leader>cx)
"
"     BufWinEnter autocmd (chat buffer only)
"         └──► GoToLastYouLine()
"
"     C-] keymap (chat buffer only)
"         └──► SendChatMessage()
"
"
"   ╔══════════════════════════════════════════════════════════════════════════╗
"   ║  IMPLEMENT FLOW  (<leader>ci on a visual selection)                      ║
"   ╚══════════════════════════════════════════════════════════════════════════╝
"
"     ClaudeImplement()
"         └──► ClaudeQueryInternal()
"                   ├── [stream cb] ──► StreamingImplementResponse()
"                   └── [final  cb] ──► FinalImplementResponse()
"                                           ├──► LogImplementInChat()
"                                           │        ├──► GetOrCreateChatWindow()
"                                           │        │        └──► OpenClaudeChat()
"                                           │        ├──► AppendResponse()
"                                           │        ├──► CloseCurrentInteractionCodeBlocks()
"                                           │        ├──► AppendTokenUsage()
"                                           │        └──► PrepareNextInput()
"                                           ├──► ExtractCodeFromMarkdown()
"                                           └──► ApplyCodeChangesDiff()
"                                                    └──► ApplyChange()
"
"
"   ╔══════════════════════════════════════════════════════════════════════════╗
"   ║  CHAT FLOW  (C-] in chat window)                                         ║
"   ╚══════════════════════════════════════════════════════════════════════════╝
"
"     SendChatMessage()
"         ├──► ParseChatBuffer()                ← parses the whole chat buffer
"         │        ├──► ProcessLine()
"         │        │        ├──► AddMessageToList()
"         │        │        ├──► InitMessage()
"         │        │        ├──► ParseToolUse()
"         │        │        ├──► InitToolResult()
"         │        │        └──► AppendContent()
"         │        └──► AddMessageToList()
"         ├──► ResponseExtractToolUses()        ← any pending tool calls?
"         ├──► ExecuteTool()                    ← (if tools pending)
"         │        ├──► ExecutePythonCode()
"         │        ├──► ExecuteShellCommand()
"         │        ├──► ExecuteOpenTool()
"         │        ├──► ExecuteNewTool()
"         │        └──► ExecuteOpenWebTool()    ◄── also used by web_search
"         ├──► AppendToolResult()               ← write result into chat buffer
"         ├──► GetBuffersContent()              ← collect all open buffers
"         └──► ClaudeQueryInternal()
"                  ├── [stream cb] ──► StreamingChatResponse()
"                  │                        └──► GetOrCreateChatWindow()
"                  │                                 └──► OpenClaudeChat()
"                  └── [final  cb] ──► FinalChatResponse()
"                                           ├──► ParseChatBuffer()
"                                           ├──► ResponseExtractToolUses()
"                                           ├──► ApplyChangesFromResponse()
"                                           │        ├──► ResponseExtractChanges()
"                                           │        │        └──► ProcessCodeBlock()
"                                           │        │                 └──► (populates changes dict)
"                                           │        └──► ApplyCodeChangesDiff()
"                                           │                 └──► ApplyChange()
"                                           ├── [tools found] ──► SendChatMessage()  ◄─ (loops back!)
"                                           └── [no tools]
"                                                   ├──► CloseCurrentInteractionCodeBlocks()
"                                                   ├──► AppendTokenUsage()
"                                                   └──► PrepareNextInput()
"
"
"   ╔══════════════════════════════════════════════════════════════════════════╗
"   ║  CANCEL FLOW  (<leader>cx)                                               ║
"   ╚══════════════════════════════════════════════════════════════════════════╝
"
"     CancelClaudeResponse()
"         ├──► AppendResponse()
"         ├──► CloseCurrentInteractionCodeBlocks()
"         ├──► AppendTokenUsage()
"         └──► PrepareNextInput()
"
"
"   ╔══════════════════════════════════════════════════════════════════════════╗
"   ║  HTTP / STREAMING LAYER  (inside ClaudeQueryInternal)                    ║
"   ╚══════════════════════════════════════════════════════════════════════════╝
"
"     ClaudeQueryInternal()
"         │   (starts a curl / python3 job, wires up callbacks)
"         │
"         ├── Vim  stdout ──► HandleStreamOutput()
"         │                        ├──► AppendToolUse()
"         │                        └──► DisplayTokenUsageAndCost()
"         ├── Nvim stdout ──► HandleStreamOutputNvim()
"         │                        └──► HandleStreamOutput()   (delegates)
"         │
"         ├── Vim  stderr ──► HandleJobError()
"         ├── Nvim stderr ──► HandleJobErrorNvim()
"         │                        └──► HandleJobError()       (delegates)
"         │
"         ├── Vim  exit   ──► HandleJobExit()
"         └── Nvim exit   ──► HandleJobExitNvim()
"                                  └──► HandleJobExit()        (delegates)
"
"
"   ╔══════════════════════════════════════════════════════════════════════════╗
"   ║  CHAT WINDOW SETUP  (one-time, on first OpenClaudeChat)                  ║
"   ╚══════════════════════════════════════════════════════════════════════════╝
"
"     OpenClaudeChat()
"         ├──► SetupClaudeChatSyntax()
"         └──► GoToLastYouLine()
"
"     GetOrCreateChatWindow()        ← called by many streaming functions
"         └──► OpenClaudeChat()      (only if buffer not yet loaded)
" ============================================================================


" ============================================================================
"   These are the "live wires" that carry data between functions across time:
"
"   ┌─────────────────────────────────────────────────────────────────────────┐
"   │  s:current_chat_job                                                     │
"   │                                                                         │
"   │  Set by ── SendChatMessage()      (job handle / channel)                │
"   │            FinalImplementResponse() also clears it                      │
"   │  Read by ── CancelClaudeResponse()  (to stop the job)                   │
"   │  Cleared by FinalChatResponse()  /  CancelClaudeResponse()              │
"   │             FinalImplementResponse()                                    │
"   └─────────────────────────────────────────────────────────────────────────┘
"
"   ┌─────────────────────────────────────────────────────────────────────────┐
"   │  s:implement_response                                                   │
"   │                                                                         │
"   │  Created & grown by ── StreamingImplementResponse()  (delta by delta)   │
"   │  Consumed by ────────── FinalImplementResponse()                        │
"   │                           └─ LogImplementInChat()                       │
"   │                           └─ ExtractCodeFromMarkdown()                  │
"   │  Deleted by ─────────── FinalImplementResponse()                        │
"   └─────────────────────────────────────────────────────────────────────────┘
"
"   ┌─────────────────────────────────────────────────────────────────────────┐
"   │  s:current_tool_call   { id, name, input }                              │
"   │                                                                         │
"   │  Created by ── HandleStreamOutput()  on content_block_start (tool_use)  │
"   │  Grown by ──── HandleStreamOutput()  on input_json_delta                │
"   │  Consumed by ─ HandleStreamOutput()  on content_block_stop              │
"   │                  └─ AppendToolUse()  (writes to chat buffer)            │
"   │  Deleted by ── HandleStreamOutput()  on content_block_stop              │
"   │                                                                         │
"   │  Lifetime: one tool call within one streaming response                  │
"   └─────────────────────────────────────────────────────────────────────────┘
"
"   ┌─────────────────────────────────────────────────────────────────────────┐
"   │  s:stored_input_tokens                                                  │
"   │                                                                         │
"   │  Set by ──── HandleStreamOutput()  on message_start event               │
"   │  Consumed by DisplayTokenUsageAndCost()  on message_delta event         │
"   │  Deleted by DisplayTokenUsageAndCost()  after use                       │
"   │                                                                         │
"   │  Bridges two separate SSE events that carry the two halves of the       │
"   │  token count (input tokens arrive first, output tokens arrive last)     │
"   └─────────────────────────────────────────────────────────────────────────┘
"
"   ┌─────────────────────────────────────────────────────────────────────────┐
"   │  s:last_token_usage   (formatted string)                                │
"   │                                                                         │
"   │  Set by ──── DisplayTokenUsageAndCost()  (also echom's it immediately)  │
"   │  Consumed by AppendTokenUsage()  (writes it into chat buffer)           │
"   │  Deleted by AppendTokenUsage()  after writing                           │
"   └─────────────────────────────────────────────────────────────────────────┘
" ============================================================================


" ============================================================================
" Configuration variables
" ============================================================================
" Sets up all global config variables with defaults if not already defined.
" Users can override these in their .vimrc before the plugin loads.
" - g:claude_api_key: Anthropic API key for direct API access
" - g:claude_api_url: The endpoint URL for the Anthropic messages API
" - g:claude_model: The Claude model name to use (e.g. claude-sonnet-4-6)
" - g:claude_use_bedrock: If 1, use AWS Bedrock instead of direct Anthropic API
" - g:claude_use_1m_context: If 1, enables the 1M token context beta header
" - g:claude_bedrock_region: AWS region for Bedrock requests
" - g:claude_bedrock_model_id: Bedrock-specific model identifier string
" - g:claude_aws_profile: AWS credentials profile name (empty = use default)
" - g:claude_map_implement: Visual-mode keybinding that invokes `:ClaudeImplement` on the selected lines
" - g:claude_map_open_chat: Keybinding to open the chat window
" - g:claude_map_send_chat_message: Keybinding to send a chat message
" - g:claude_map_cancel_response: Keybinding to cancel an in-flight response
" ============================================================================


" ============================================================================
" Keybindings setup
" ============================================================================

" ============================================================================
" s:SetupClaudeKeybindings()
" ============================================================================
" Called once on VimEnter via an autocommand.
" Registers all user-facing Ex commands and sets up keybindings:
"   - ClaudeImplement: a range command taking an instruction string; calls
"     s:ClaudeImplement() on the visually selected lines.
"   - ClaudeChat: opens (or focuses) the Claude Chat window.
"   - ClaudeCancel: cancels any in-flight streaming Claude response.
" The keybindings are read from g:claude_map_* so users can remap them.
" ============================================================================

" ============================================================================
" s:ClaudeLoadPrompt(prompt_type)
" ============================================================================
" Reads a prompt template from a markdown file next to this script.
" The file is named  claude_<prompt_type>_prompt.md  (e.g.
" claude_system_prompt.md, claude_implement_prompt.md).
" Returns the file contents as a list of lines.
" Used to initialise g:claude_default_system_prompt and
" g:claude_implement_prompt at startup.
" ============================================================================


" ============================================================================
" Claude API
" ============================================================================

" ============================================================================
" s:ClaudeQueryInternal(messages, system_prompt, tools,
"                        stream_callback, final_callback)
" ============================================================================
" Core function that fires off an async HTTP request to the Claude API
" (or AWS Bedrock) and wires up callbacks for the streaming response.
"
" Parameters:
"   messages        – List of {role, content} dicts representing the
"                     conversation history in Anthropic API format.
"   system_prompt   – String inserted as the system turn.
"   tools           – List of tool-definition dicts (may be empty).
"   stream_callback – Funcref(delta) called repeatedly as text arrives.
"   final_callback  – Funcref() called once when the stream is complete.
"
" Behaviour differs by backend:
"   Bedrock: builds a command that invokes claude_bedrock_helper.py with
"            the relevant args (region, model-id, messages, system prompt,
"            optional tools, optional AWS profile).
"   Direct API: builds a curl command with the required Anthropic headers
"            (Content-Type, x-api-key, anthropic-version, optional 1M-context
"            beta header).  The JSON body is written to a temp file to avoid
"            shell argument-length limits, then passed to curl with
"            --data-binary @<tmpfile>.
"
" The job is started with job_start() (Vim) or jobstart() (Neovim), hooking
" stdout → s:HandleStreamOutput*, stderr → s:HandleJobError*, and
" exit → s:HandleJobExit*.  The job handle is returned to the caller so it
" can be stored for later cancellation.
" ============================================================================

" ============================================================================
" s:DisplayTokenUsageAndCost(json_data)
" ============================================================================
" Receives the JSON string from a message_delta SSE event (already extracted
" by s:HandleStreamOutput), decodes it, and prints a token-usage summary.
" Also accumulates s:total_input_tokens, s:total_cache_creation_tokens,
" s:total_cache_read_tokens, and s:total_output_tokens across tool-use turns
" before computing cost. and prints a one-line token-usage summary to the
" message area via echom, e.g.:
"   Token usage - Input: 1234 ($0.0037), Output: 456 ($0.0068)
" Pricing is looked up from the s:claude_pricing dict by g:claude_model
" (defaulting to $3/M input, $15/M output). Cache-creation tokens are billed
" at 1.25× and cache-read tokens at 0.10× the input rate.
" Input token count is taken from s:stored_input_tokens which was saved
" earlier when the 'message_start' event arrived; that script-local
" variable is deleted afterwards to avoid stale data.
" ============================================================================

" ============================================================================
" s:HandleStreamOutput(stream_callback, final_callback, channel, msg)
" ============================================================================
" Vim-flavour stdout callback. Receives raw text from curl's SSE stream,
" splits it on newlines, and dispatches each line:
"
"   event: ping                → silently ignored
"   event: error               → calls stream_callback with an error string,
"                                then final_callback
"   event: message_stop        → calls final_callback (stream is done)
"   event: message_start/…     → recognised event names, no further action
"   data: <json>               → decoded and handled by type:
"       message_start          → stores input_tokens, cache_creation_input_tokens,
"                                and cache_read_input_tokens from the usage block
"                                into s:stored_input_tokens, s:stored_cache_creation_tokens,
"                                and s:stored_cache_read_tokens respectively.
"       message_delta          → calls s:DisplayTokenUsageAndCost
"       content_block_start    → if content_block.type == 'tool_use', starts
"                                accumulating a new tool call in
"                                s:current_tool_call
"       content_block_delta /
"         input_json_delta     → appends partial JSON to s:current_tool_call.input
"       content_block_stop     → if a tool call was being built, decodes its
"                                input JSON and calls s:AppendToolUse to write
"                                it into the chat buffer
"       delta.text present     → calls stream_callback(delta) to stream text
"       anything else          → forwards raw line to stream_callback as a
"                                warning string
" ============================================================================

" ============================================================================
" s:HandleJobError / s:HandleJobErrorNvim
" ============================================================================
" Stderr callbacks (Vim / Neovim variants).
" Any text arriving on stderr is passed straight to stream_callback as an
" error string, then final_callback is invoked to clean up.
" ============================================================================

" ============================================================================
" s:HandleJobExit / s:HandleJobExitNvim
" ============================================================================
" Exit callbacks (Vim / Neovim variants).
" Always deletes the temporary JSON file that was written by
" s:ClaudeQueryInternal.  If the exit status is non-zero, reports an error
" via stream_callback and calls final_callback.
" ============================================================================

" ============================================================================
" s:HandleStreamOutputNvim / (Nvim wrappers)
" ============================================================================
" Neovim's job callbacks receive data as a list of strings rather than a
" single string, so these thin wrappers iterate over that list and delegate
" each item to the corresponding Vim-flavour handler above.
" ============================================================================

" ============================================================================
" s:HandleJobError / s:HandleJobErrorNvim
" ============================================================================
" Stderr callbacks (Vim / Neovim variants).
" Any text arriving on stderr is passed straight to stream_callback as an
" error string, then final_callback is invoked to clean up.
" ============================================================================

" ============================================================================
" s:HandleJobExit / s:HandleJobExitNvim
" ============================================================================
" Exit callbacks (Vim / Neovim variants).
" Always deletes the temporary JSON file that was written by
" s:ClaudeQueryInternal.  If the exit status is non-zero, reports an error
" via stream_callback and calls final_callback.
" ============================================================================


" ============================================================================
" Diff View
" ============================================================================

" ============================================================================
" s:ApplyChange(normal_command, content)
" ============================================================================
" Low-level helper that applies a text change to the current buffer by
" running an arbitrary Normal-mode command followed by pasting content via
" the expression register (<C-r>=).
" Saves and restores the window view and the 'paste' option so that
" auto-indentation does not corrupt the inserted text.
" The literal string '<CR>' inside normal_command is translated to a real
" carriage-return before execution.
" ============================================================================

" ============================================================================
" s:ApplyCodeChangesDiff(bufnr, changes)
" ============================================================================
" Opens a side-by-side diff showing the proposed edits for buffer `bufnr`.
"
" Steps:
"  1. Finds (or creates) a window that displays the target buffer. If the
"     buffer isn't currently visible in any window, it splits and switches
"     to it.
"  2. Opens a new scratch buffer to the right (rightbelow vnew), copies the
"     current content of the target buffer into it, and sets the same
"     filetype so syntax highlighting matches.
"  3. Iterates over the `changes` list and applies each one to the scratch
"     buffer:
"       type='content'  → calls s:ApplyChange() with a Normal-mode command
"                         and replacement text.
"       type='vimexec'  → runs each command string with :execute (falling
"                         back to :normal if :execute fails).
"     Failed edits are collected and reported as warnings but do not abort
"     the remaining changes.
"  4. Calls :diffthis on both the scratch buffer and the original buffer,
"     producing a standard Vim diff view. The user can then inspect the diff,
"     use :diffget / do to accept hunks, and :q to close the scratch buffer.
"  5. Returns to whatever window was active before this function was called.
" ============================================================================


" ============================================================================
" Tool Integration
" ============================================================================

" ============================================================================
" g:claude_tools  (configuration list)
" ============================================================================
" Defines the tools that Claude is allowed to call during a chat session.
" Each entry is a dict matching the Anthropic tool-definition schema:
"   name           – identifier Claude uses when it wants to call the tool
"   description    – natural-language description shown to the model
"   input_schema   – JSON-Schema object describing the expected arguments
"
" Built-in tools:
"   python    – runs a Python one-liner with `python3 -c` and returns stdout.
"   shell     – runs an arbitrary shell command and returns stdout + stderr
"               + exit status.
"   open      – opens a file/directory in a hidden Vim window and returns
"               the buffer name (or ERROR if the path doesn't exist / is
"               empty).
"   new       – creates a new empty file on disk, opens it in Vim, and
"               returns the buffer name (or ERROR if the file already
"               exists).
"   open_web  – fetches a URL with `elinks -dump` and returns the buffer
"               name of the scratch window containing the rendered text.
"   web_search– URL-encodes the query and delegates to open_web with a
"               Google search URL.
" ============================================================================

" ============================================================================
" s:ExecuteTool(tool_name, arguments)
" ============================================================================
" Dispatcher: maps the tool name string that Claude requested to the
" appropriate Vim function, passing the relevant argument fields.
" web_search is special-cased here: it percent-encodes the query string
" with a py3eval one-liner before forwarding to s:ExecuteOpenWebTool.
" Returns the string result that will be fed back to Claude as a tool
" result message.
" ============================================================================

" ============================================================================
" s:ExecutePythonCode(code)
" ============================================================================
" Asks the user for confirmation (y/n) before running `python3 -c <code>`.
" This safety prompt prevents Claude from executing arbitrary Python without
" user awareness. If the user approves, runs the code with system() and
" returns the combined output. If denied, returns a cancellation message
" which is sent back to Claude so it knows the execution didn't happen.
" The prompt also mentions C-C / C-] to guide the user on pause/resume.
" ============================================================================

" ============================================================================
" s:ExecuteShellCommand(command)
" ============================================================================
" Same confirmation pattern as s:ExecutePythonCode, but for shell commands.
" Runs the command with system(), captures stdout, and appends the numeric
" exit status on a final line so Claude can detect failures.
" ============================================================================

" ============================================================================
" s:ExecuteOpenTool(path)
" ============================================================================
" Opens `path` in a temporary top-left 1-line window using :edit.
" If the resulting buffer is empty (file not found or unreadable) the window
" is closed and an ERROR string is returned.
" Otherwise the window is left open (so its content is available as a
" buffer) and the buffer name is returned. The original window is restored
" in all cases.
" ============================================================================

" ============================================================================
" s:ExecuteNewTool(path)
" ============================================================================
" Guards against overwriting existing files by checking filereadable().
" If the file already exists, returns an ERROR string immediately.
" Otherwise opens a blank top-left window, writes it to disk with
" :silent write (creating the file), and returns the buffer name so
" Claude knows which buffer to target when writing content into the file.
" ============================================================================

" ============================================================================
" s:ExecuteOpenWebTool(url)
" ============================================================================
" Fetches url using `:r !elinks -dump` (a terminal browser that converts HTML
" to plain text) and places the result in a scratch buffer.
" The buffer is named after the URL so it can be referenced later.
" Returns the buffer name on success, or an ERROR string if elinks fails.
" Used both directly (open_web tool) and indirectly (web_search tool).
" ============================================================================


" ============================================================================
" ClaudeImplement
" ============================================================================

" ============================================================================
" s:LogImplementInChat(instruction, implement_response, bufname,
"                       start_line, end_line)
" ============================================================================
" Records a ClaudeImplement interaction in the chat window so there is a
" permanent, scrollable log of what was asked and what was generated.
" - Removes the trailing blank "You:" prompt line if present.
" - Appends a "You: Implement in <file> (lines N-M): <instruction>" line.
" - Shows the first and last lines of the selected range (with "..." in
"   between when the range is more than 2 lines) as context.
" - Appends Claude's full response via s:AppendResponse().
" - Calls s:CloseCurrentInteractionCodeBlocks() and s:PrepareNextInput()
"   to tidy up the chat buffer ready for the next message.
" ============================================================================

" ============================================================================
" s:ClaudeImplement(line1, line2, instruction)
" ============================================================================
" Entry point for the :ClaudeImplement range command (mapped to <leader>ci
" in visual mode by default).
"
" 1. Collects the lines in the visual selection as a single string.
" 2. Builds a system prompt by wrapping the selected code in <code>…</code>
"    tags and appending the contents of claude_implement_prompt.md.
"    This prompt instructs Claude to return its answer as a fenced code block.
" 3. Sends a single-turn message (the user's instruction) to Claude with no
"    tools enabled, using s:ClaudeQueryInternal.
" 4. Streams the response into s:implement_response via
"    s:StreamingImplementResponse, then on completion calls
"    s:FinalImplementResponse to extract and apply the code.
" Function to implement code based on instructions
" ============================================================================

" ============================================================================
" s:ExtractCodeFromMarkdown(markdown)
" ============================================================================
" Strips the fenced code block delimiters (``` lines) from a markdown string
" and returns only the code inside the first code block found.
" Used by s:FinalImplementResponse to pull the bare code out of Claude's
" markdown-formatted reply before inserting it into the buffer.
" ============================================================================

" ============================================================================
" s:StreamingImplementResponse(delta)
" ============================================================================
" Stream callback for ClaudeImplement. Simply accumulates all arriving text
" deltas into the script-local s:implement_response string. No UI update is
" done during streaming for implement — the result is only shown once the
" full response has arrived.
" ============================================================================

" ============================================================================
" s:FinalImplementResponse(line1, line2, bufnr, bufname, winid, instruction)
" ============================================================================
" Final callback for ClaudeImplement, called when the stream ends.
" 1. Returns to the original window where the implement command was invoked.
" 2. Logs the full interaction in the chat window via s:LogImplementInChat.
" 3. Extracts the bare code from the markdown response with
"    s:ExtractCodeFromMarkdown.
" 4. Builds a single 'content' change that replaces the originally selected
"    lines (line1 to line2) with the extracted code, using a Visual-mode
"    selection + 'c' (change) as the Normal-mode command.
" 5. Passes that change to s:ApplyCodeChangesDiff() to show the result in a
"    side-by-side diff view so the user can review before accepting.
" 6. Prints a hint reminding the user how to work with the diff (:diffget /
"    do to accept hunks, :q to close).
" 7. Cleans up s:implement_response and s:current_chat_job.
" ============================================================================


" ============================================================================
" ClaudeChat
" ============================================================================


" ----- Chat service functions

" ============================================================================
" s:GetOrCreateChatWindow()
" ============================================================================
" Ensures the Claude Chat buffer exists and is loaded. If it doesn't exist
" yet (bufnr returns -1) or has been unloaded, calls s:OpenClaudeChat() to
" create it fresh. Returns a three-element list:
"   [chat_bufnr, chat_winid, current_winid]
" where current_winid is the window that was active before this call, so
" callers can restore it with win_gotoid() when they are done.
" ============================================================================

" ============================================================================
" s:GetClaudeIndent()
" ============================================================================
" Returns the string used to indent continuation lines inside the chat
" buffer. Respects the buffer's expandtab / shiftwidth / tabstop settings:
"   expandtab on  → returns shiftwidth spaces
"   expandtab off → returns the appropriate number of tab characters
" This indentation is used to visually mark lines that belong to a Claude
" or Tool response, and is also relied upon by the parser to distinguish
" continuation lines from new speaker lines.
" ============================================================================

" ============================================================================
" s:AppendResponse(response)
" ============================================================================
" Appends a complete Claude response to the current buffer (expected to be
" the chat buffer).
" - Single-line response: appended as "Claude: <text>" on one line.
" - Multi-line response: starts with a bare "Claude:" line, then each
"   subsequent line is indented with s:GetClaudeIndent(). Blank lines are
"   preserved as empty strings (no indent added) to keep paragraph spacing.
" ============================================================================

" ----- Chat window UX

" ============================================================================
" GetChatFold(lnum)
" ============================================================================
" Fold-expression function intended for use with 'foldmethod=expr' in the
" chat buffer (set via 'setlocal foldexpr=GetChatFold(v:lnum)').
" Returns a fold-level descriptor string for each line, following Vim's
" foldexpr conventions:
"
"   '0'   → not part of any fold (terminates any open fold)
"   '='   → same fold level as the previous line (continue current fold)
"   '>1'  → start a new level-1 fold on this line
"   '>2'  → start a new level-2 fold on this line (nested inside level-1)
"   '<2'  → end a level-2 fold on this line
"
" The intended fold structure is:
"   Level 1 folds: each complete "You:" / "System prompt:" interaction block,
"                  so entire exchanges can be collapsed in the chat history.
"   Level 2 folds: fenced code blocks (``` ... ```) nested inside a level-1
"                  fold, so individual code snippets can be collapsed
"                  independently while keeping the surrounding text visible.
"
" Rules applied per line:
"   "^You:" or "^System prompt:"  → '>1' (start a new top-level fold)
"   indented, blank, or "^.*:"    → '=' by default (continue current fold),
"                                   UNLESS the line is "^\s*```":
"                                     if already at level 1 → '>2' (open code fold)
"                                     otherwise             → '<2' (close code fold)
"   anything else                 → '0' (outside any fold)
" ============================================================================

" ============================================================================
" g:SetupClaudeChatSyntax()
" ============================================================================
" Defines the syntax highlighting rules for the Claude Chat buffer.
" Only runs once per buffer (guarded by b:current_syntax).
" Includes the standard markdown syntax as a sub-syntax (@markdown group)
" so that Claude's responses render with markdown highlighting.
" Defines these additional regions/matches on top:
"   claudeChatSystem        – the indented system-prompt block at the top
"   claudeChatSystemKeyword – the "System prompt:" label itself
"   claudeChatYou           – "You:" speaker label
"   claudeChatClaude        – "Claude:" / "Claude...:" speaker label
"   claudeChatToolUse       – "Tool use (...):" label
"   claudeChatToolResult    – "Tool result (...):" label
"   claudeChatCodeBlock     – fenced code blocks inside responses (no spell)
" Also clears markdownCodeBlock to prevent indented lines from being treated
" as code blocks by the markdown sub-syntax (which would over-match here).
" ============================================================================

" ============================================================================
" s:GoToLastYouLine()
" ============================================================================
" Moves the cursor to the end of the last line of the buffer (G$).
" Used as a BufWinEnter autocommand so that every time the chat window is
" displayed the cursor is positioned at the active "You:" input line at the
" bottom, ready for the user to type.
" ============================================================================

" ============================================================================
" s:OpenClaudeChat()
" ============================================================================
" Opens the Claude Chat window or focuses it if already open.
"
" First-time open (buffer doesn't exist yet):
"   1. Creates a new bottom-right window ('botright new') named 'Claude Chat'.
"   2. Configures it as a scratch buffer (buftype=nofile, noswapfile,
"      bufhidden=hide) with linebreak wrapping for readability.
"   3. Calls g:SetupClaudeChatSyntax() to apply chat-specific highlighting.
"   4. Populates the buffer with:
"        - The system prompt (from g:claude_default_system_prompt), with
"          each continuation line tab-indented.
"        - A usage hint line.
"        - A blank line followed by an initial "You: " prompt.
"   5. Registers a BufWinEnter autocommand that keeps the cursor at the
"      bottom whenever the window is re-entered.
"   6. Registers the buffer-local C-] mapping (g:claude_map_send_chat_message)
"      for both insert and normal mode to call s:SendChatMessage('Claude:').
"
" Subsequent opens (buffer already loaded):
"   - If the buffer is visible in a window, moves focus there.
"   - If the buffer is loaded but not displayed, splits and shows it.
"
" In both cases finishes by calling s:GoToLastYouLine().
" ============================================================================

" ----- Chat parser (to messages list)

" ============================================================================
" s:AddMessageToList(messages, message)
" ============================================================================
" Finalises a message dict that was being accumulated by the parser and
" appends it to the messages list (only if role is non-empty).
" Handles three cases:
"   Plain text message   → {role, content: joined string}
"   Message with tool_use→ content becomes a list:
"                          [{type:'text', text:…}, <tool_use dict>]
"   Message with tool_result → content becomes a list containing just
"                          the tool_result dict (as required by the API).
" NOTE: currently only handles one tool_use or tool_result per message.
" ============================================================================

" ============================================================================
" s:InitMessage(role, line)
" ============================================================================
" Creates a fresh message accumulator dict for the given role ('user' or
" 'assistant'). The first line's speaker prefix (e.g. "You: ", "Claude: ")
" is stripped with a regex, and the remaining text becomes the first element
" of the content list. tool_use and tool_result are initialised to empty
" dicts so the parser can check emptiness with !empty().
" ============================================================================

" ============================================================================
" s:ParseToolUse(line)
" ============================================================================
" Parses a "Tool use (<id>): <name>" line from the chat buffer back into a
" tool_use dict suitable for the Anthropic API:
"   { type: 'tool_use', id: <id>, name: <name>, input: {} }
" Returns an empty dict if the line doesn't match the expected format.
" ============================================================================

" ============================================================================
" s:InitToolResult(line)
" ============================================================================
" Parses a "Tool result (<id>):" line and creates a fresh message
" accumulator whose tool_result field holds a skeleton tool_result dict:
"   { type: 'tool_result', tool_use_id: <id>, content: '' }
" Subsequent indented lines will be appended to content by s:AppendContent.
" ============================================================================

" ============================================================================
" s:AppendContent(message, line)
" ============================================================================
" Appends a continuation line to the message currently being accumulated,
" routing it to the right place depending on message state:
"
"   tool_use present + line matches "Input:" → decodes the JSON on that line
"                                              and stores it as tool_use.input
"   tool_use present + tool is 'python'      → strips indentation and appends
"                                              to tool_use.input.code (handles
"                                              multi-line Python snippets)
"   tool_result present                      → strips indent and appends to
"                                              tool_result.content string
"   plain message                            → strips indent, also strips any
"                                              trailing " [APPLIED]" marker
"                                              that `s:ProcessCodeBlock`
"                                              appended to the opening ` ```
"                                              `header line of an already-
"                                              applied code block, before
"                                              adding the line to content.,
"                                              then appends to the message's
"                                              content list.
" ============================================================================

" ============================================================================
" s:ProcessLine(line, messages, current_message)
" ============================================================================
" The core line-by-line state machine of the chat buffer parser.
" Works on a copy of current_message and returns the (possibly new)
" accumulator. Recognises these speaker-prefix patterns:
"
"   "You:"         → finalises current_message into messages, starts a new
"                    'user' accumulator via s:InitMessage.
"   "Claude" (any) → finalises current_message, starts a new 'assistant'
"                    accumulator. Matches both "Claude:" and "Claude...:"
"                    (the latter is used for tool-only responses).
"   "Tool use ("   → does NOT finalise; instead calls s:ParseToolUse and
"                    stores the result in current_message.tool_use, so the
"                    tool call is attached to the preceding Claude message.
"   "Tool result (" → finalises current_message, starts a fresh user message
"                    whose tool_result field is populated via s:InitToolResult.
"   anything else  → if a message is in progress, delegates to
"                    s:AppendContent to accumulate the line as content.
" ============================================================================

" ============================================================================
" s:ParseChatBuffer()
" ============================================================================
" Reads the entire chat buffer from line 1 to '$' and converts it into the
" data structures the Anthropic API expects.
"
" Two-pass concerns handled in a single linear scan:
"   - Lines beginning with "System prompt:" start the system prompt block;
"     subsequent indented lines are accumulated into l:system_prompt.
"   - Once a non-indented, non-system-prompt line is seen, system prompt
"     parsing ends and the conversation parser (s:ProcessLine) takes over.
"
" Returns a two-element list:
"   [ messages, system_prompt_string ]
" where messages is the filtered list produced by s:ProcessLine (empty
" content entries are removed) and system_prompt_string is the system prompt
" lines joined with newlines.
" ============================================================================

" ----- Sending messages

" ============================================================================
" s:GetBuffersContent()
" ============================================================================
" Collects the content of every listed, visible, non-chat buffer and returns
" it as a list of {name, contents} dicts. "Visible" means the buffer has at
" least one open window (win_findbuf returns non-empty).
" This list is used by s:SendChatMessage to prepend all open buffer contents
" to the system prompt, giving Claude full awareness of the current workspace.
" ============================================================================

" ============================================================================
" s:SendChatMessage(prefix)
" ============================================================================
" The main entry point for sending a user message. Called when the user
" presses C-] (or the configured keybinding) in the chat window.
" Also called recursively by s:FinalChatResponse when tool results need to
" be sent back to Claude.
"
" Steps:
"  1. Calls s:ParseChatBuffer() to get the current messages + system prompt.
"  2. Checks whether the last assistant message contains any tool_use blocks
"     (via s:ResponseExtractToolUses). If so, executes each tool with
"     s:ExecuteTool, appends the result to the chat buffer via
"     s:AppendToolResult, then re-parses the buffer so the tool results are
"     included in the messages sent to the API.
"  3. Builds a buffer-content preamble (s:GetBuffersContent) and prepends it
"     to the system prompt so Claude can see all open files.
"  4. Appends a "<prefix> " placeholder line to the chat buffer and moves
"     the cursor there, so the user can see the response appearing in real
"     time as it streams in.
"  5. Fires off the async API call via s:ClaudeQueryInternal, using
"     s:StreamingChatResponse as the stream callback and
"     s:FinalChatResponse as the final callback.
"  6. Stores the job handle in s:current_chat_job so it can be cancelled
"     via s:CancelClaudeResponse.
" ============================================================================

" ----- Handling responses: Tool use

" ============================================================================
" s:ResponseExtractToolUses(messages)
" ============================================================================
" Inspects the last message in the messages list. If its content is a list
" (i.e. it contains structured blocks rather than plain text) it filters and
" returns only the entries whose type is 'tool_use'. Returns an empty list
" if there are no messages, if the last message has plain-text content, or
" if there are no tool_use blocks.
" Used both in s:SendChatMessage (to decide whether to execute tools before
" sending) and in s:FinalChatResponse (to decide whether to auto-continue).
" ============================================================================

" ============================================================================
" s:AppendToolUse(tool_call_id, tool_name, tool_input)
" ============================================================================
" Writes a tool-use record into the chat buffer in the format the parser
" can later reconstruct:
"   Tool use (<id>): <name>
"     <indented representation of input>
" For the 'python' tool, the code is written line-by-line (indented) so it
" is human-readable in the chat log. For all other tools, the input dict is
" serialised as a single JSON line prefixed with "Input: ".
" Also handles the edge case where the preceding "Claude: " line is empty
" (a tool-only response with no text): rewrites it to
" "Claude...: (tool-only response)" so the parser still recognises it as an
" assistant turn.
" ============================================================================

" ============================================================================
" s:AppendToolResult(tool_call_id, result)
" ============================================================================
" Writes a tool-result record into the chat buffer:
"   Tool result (<id>):
"     <indented result lines>
" Each line of the result string is individually indented so the parser can
" reconstruct the full multi-line result when it encounters these lines via
" s:AppendContent.
" ============================================================================

" ----- Handling responses: Code changes

" ============================================================================
" s:ProcessCodeBlock(block, all_changes)
" ============================================================================
" Processes a single fenced code block found in the latest Claude response
" and registers it as a pending change in the all_changes dict.
"
" The code block header (the text after the opening ```) is expected to
" follow the convention:  <filetype> <buffername>[:<normal_command>]
"   filetype       – used to set the scratch buffer's filetype in the diff
"                    view; if 'vimexec', the block is treated as Vim commands
"                    rather than file content.
"   buffername     – matched against open buffers with bufnr(); changes are
"                    grouped by buffer number in all_changes.
"   normal_command – optional Normal-mode command controlling where the
"                    content is inserted (defaults to 'Go<CR>' which appends
"                    at end of file).
"
" For 'vimexec' blocks, adds a {type:'vimexec', commands:[…]} entry.
" For content blocks, adds a {type:'content', normal_command:…, content:…}
" entry. In both cases, marks the opening ``` line in the chat buffer with
" " [APPLIED]" so the parser knows not to re-apply it on the next send.
" ============================================================================

" ============================================================================
" s:ResponseExtractChanges()
" ============================================================================
" Scans the most recent Claude response block in the chat buffer (from the
" last "Claude:" line to end of buffer) looking for fenced code blocks whose
" headers follow the <filetype> <buffername>[:<command>] convention.
" Builds and returns an all_changes dict keyed by buffer number, where each
" value is a list of change dicts ready for s:ApplyCodeChangesDiff.
" Handles unclosed code blocks (e.g. if the stream was cancelled mid-block)
" by treating end-of-buffer as the implicit closing delimiter.
" ============================================================================

" ============================================================================
" s:ApplyChangesFromResponse()
" ============================================================================
" Calls s:ResponseExtractChanges() and, if any code-block changes were
" found, iterates over the all_changes dict and calls s:ApplyCodeChangesDiff
" for each target buffer, passing its list of changes. After processing all
" buffers, moves the cursor to the end of the chat buffer with G.
" Called at the end of every complete Claude response to automatically
" surface any code edits the model proposed.
" ============================================================================

" ----- Handling responses

" ============================================================================
" s:ClosePreviousFold()
" ============================================================================
" Intended to be called after a complete Claude response has been appended
" to the chat buffer, in order to collapse the just-finished interaction
" fold so the chat log stays compact.
"
" Saves the cursor position, then navigates with '[z' (move to the start of
" the current fold) and 'k' (up one line) and '[z' again followed by 'zc'
" (close fold) to collapse the previous interaction's level-1 fold.
" The cursor is restored to its saved position afterwards.
"
" Emits a warning if the fold at the target line is not actually closed
" after the attempt (foldclosed('.') == -1 means no fold is closed there).
" ============================================================================

" ============================================================================
" s:CloseCurrentInteractionCodeBlocks()
" ============================================================================
" Placeholder / hook for fold management. Currently the folding code is
" commented out, but the function still saves and restores the cursor
" position and navigates to the start of the current fold with [z.
" Its intended purpose (when folding is re-enabled) is to collapse all
" level-2 folds (i.e. code blocks) within the current interaction so that
" the chat log stays compact after a response is complete.
" ============================================================================

" ============================================================================
" s:PrepareNextInput()
" ============================================================================
" Appends two lines to the chat buffer — a blank separator line and a fresh
" "You: " prompt — then moves the cursor to the end of that line (G$).
" Called after every complete response (and after cancellation) to leave the
" chat buffer in a state where the user can immediately start typing their
" next message.
" ============================================================================

" ============================================================================
" s:StreamingChatResponse(delta)
" ============================================================================
" Stream callback for chat responses. Called repeatedly with small text
" deltas as they arrive from the API.
"
" For each delta:
"  1. Ensures the chat window is open via s:GetOrCreateChatWindow and
"     temporarily moves focus there.
"  2. Splits the delta on newlines (keeping trailing empty strings with the
"     keepempty flag so that a trailing newline produces a new line).
"  3. Appends the first segment of the delta onto the current last line of
"     the buffer (no newline inserted — this continues the current line).
"  4. Any additional segments (i.e. text after a newline in the delta) are
"     appended as new indented lines.
"  5. Moves the cursor to the bottom (G) so the user sees output scroll in
"     real time, then restores focus to the original window.
" ============================================================================

" ============================================================================
" s:FinalChatResponse()
" ============================================================================
" Final callback invoked once when the Claude stream ends completely.
"
"  1. Parses the chat buffer to get the latest messages list.
"  2. Checks whether the last assistant message contains tool_use blocks.
"  3. Calls s:ApplyChangesFromResponse() to process any code-block edits
"     embedded in the response.
"  4a. If tool uses were found: calls s:SendChatMessage('Claude...:') to
"      immediately execute the tools and send a follow-up request. The
"      'Claude...:' prefix signals that this is a continuation turn rather
"      than a fresh user message.
"  4b. If no tool uses: the interaction is complete. Calls
"      s:CloseCurrentInteractionCodeBlocks() to tidy up any folds, appends
"      a fresh "You: " prompt via s:PrepareNextInput(), restores the
"      original window, and clears s:current_chat_job.
" ============================================================================

" ============================================================================
" s:AppendTokenUsage()
" ============================================================================
" A small function that writes `s:last_token_usage` into the chat buffer as
" a comment-style line, then clears it. Only acts if the variable exists (so
" it's safe to call unconditionally):
" Prints the token usage and cost in the chat.
" ============================================================================

" ============================================================================
" s:CancelClaudeResponse()
" ============================================================================
" Cancels any in-flight streaming response, bound to <leader>cx by default.
" If s:current_chat_job exists:
"   Neovim → calls jobstop() with the job ID.
"   Vim    → calls ch_close() with the channel handle.
" After stopping the job, clears s:current_chat_job, appends a
" "[Response cancelled by user]" notice to the chat buffer via
" s:AppendResponse, tidies up folds/code blocks, and adds a fresh "You: "
" prompt so the user can continue the conversation.
" If no job is running, prints a message saying there is nothing to cancel.
" ============================================================================

" ============================================================================
" s:ClaudeBatchPoll(batch_id, custom_id)
" ============================================================================
" Polls the batch API for results. Schedules itself via timer every
" g:claude_batch_poll_interval seconds until the batch ends.
" When complete, appends the result to the chat buffer.
" ============================================================================



"------------------------------------------------------------------------------
" Updates to support interacting with Qwen (local AI)
"------------------------------------------------------------------------------

" ============================================================================
" s:GetAllBufferContents()
" ============================================================================
" Iterates over every buffer slot (1 to bufnr('$')) and collects the content
" of each existing, non-empty buffer into a list of dictionaries.
" Each dictionary contains:
"   'filename'  – the buffer name, or '[No Name]' if unnamed.
"   'content'   – the full buffer text joined with newlines.
"   'buffer_id' – the buffer number.
" Buffers that do not exist or whose trimmed content is empty are skipped.
" Returns the list of buffer dictionaries.
" ============================================================================

" ============================================================================
" s:FormatAllBuffersForPrompt()
" ============================================================================
" Calls s:GetAllBufferContents() and formats the result as a single string
" suitable for injection into an LLM prompt.
" Each buffer is rendered as:
"   # Contents of <filename>
"   <content>
"   <buffer text>
"   </content>
" Sections are separated by a blank line.
" Returns the formatted string.
" ============================================================================

" ============================================================================
" s:CallQwenAsync(prompt)
" ============================================================================
" Sends a prompt to the Ollama /api/generate endpoint asynchronously using
" curl, with streaming enabled (stream: true).
" Builds a JSON payload containing:
"   'model'   – g:ai_model
"   'prompt'  – the supplied prompt string
"   'options' – num_ctx (g:ollama_num_ctx) and num_predict (g:ollama_num_predict)
" Writes the payload to a temp file and launches curl via:
"   Neovim → jobstart(), wiring stdout/stderr/exit to the Nvim handler trio.
"   Vim    → job_start(), wiring out_cb/err_cb/exit_cb to the Vim handler trio.
" Stores the running job handle in s:current_chat_job.
" ============================================================================

" ============================================================================
" s:HandleQwenStreamChunk(msg)
" ============================================================================
" Parses a raw chunk of text received from the Ollama streaming response.
" Splits the input on newlines and attempts to JSON-decode each non-empty
" line (JSONL format).  For each successfully decoded object:
"   - Extracts the 'response' field and passes any non-empty token to
"     s:StreamingChatResponse() so it is appended to the chat buffer.
"   - If the 'done' field is truthy, calls s:FinalQwenResponse() to
"     close out the interaction.
" Lines that fail JSON decoding are silently skipped.
" ============================================================================

" ============================================================================
" s:HandleQwenStream(channel, msg)
" ============================================================================
" Vim-specific stdout callback for the curl job.
" Receives a channel handle and a message string, then delegates directly
" to s:HandleQwenStreamChunk() for JSONL parsing and UI updates.
" ============================================================================

" ============================================================================
" s:HandleQwenError(channel, msg)
" ============================================================================
" Vim-specific stderr callback for the curl job.
" If the message is non-empty, surfaces it to the user by prepending
" 'Error: ' and passing it to s:StreamingChatResponse(), then calls
" s:FinalQwenResponse() to close the interaction cleanly.
" ============================================================================

" ============================================================================
" s:HandleQwenExit(tmp_file, job, status)
" ============================================================================
" Vim-specific exit callback for the curl job.
" Always deletes the temporary JSON payload file (a:tmp_file).
" If the exit status is non-zero, appends an error notice via
" s:StreamingChatResponse() and calls s:FinalQwenResponse().
" ============================================================================

" ============================================================================
" s:HandleQwenStreamNvim(job_id, data, event)
" ============================================================================
" Neovim-specific stdout callback for the curl job.
" Iterates over the list of strings in a:data (Neovim passes stdout chunks
" as a list) and delegates each entry to s:HandleQwenStreamChunk().
" ============================================================================

" ============================================================================
" s:HandleQwenErrorNvim(job_id, data, event)
" ============================================================================
" Neovim-specific stderr callback for the curl job.
" Iterates over a:data and, for each non-empty string, surfaces an error
" via s:StreamingChatResponse() and closes the interaction with
" s:FinalQwenResponse().
" ============================================================================

" ============================================================================
" s:HandleQwenExitNvim(tmp_file, job_id, exit_code, event)
" ============================================================================
" Neovim-specific exit callback for the curl job.
" Adapts Neovim's four-argument signature to the shared s:HandleQwenExit()
" implementation by forwarding tmp_file and exit_code (passing 0 as a
" placeholder for the unused job argument).
" ============================================================================

" ============================================================================
" s:FinalQwenResponse()
" ============================================================================
" Finalises a completed (or errored) Ollama streaming interaction.
" Guards against double-invocation (which can occur when both the 'done'
" JSON field and the job exit callback fire) using the flag
" s:qwen_response_finalized; returns immediately if already set.
" When called for the first time:
"   - Calls s:CloseCurrentInteractionCodeBlocks() to tidy any open folds.
"   - Calls s:PrepareNextInput() to append a fresh 'You: ' prompt.
"   - Cleans up s:current_chat_job and s:qwen_response_finalized.
" ============================================================================

